services:
  database:
    build:
      context: .
      dockerfile: dockerfile
    container_name: ${CONTAINER_NAME:-mysql}
    cap_add:
      - SYS_NICE
    networks:
      - database
    restart: always
    ports:
      - ${PORT:-3306}:3306
    volumes:
      - ${MYSQL_CONFIG_FILE_PATH:-./mysql.cnf}:/etc/mysql/conf.d/mysql.cnf
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=${MYSQL_ROOT_PASSWORD} --execute \"SHOW DATABASES;\""
      interval: 10s
      timeout: 20s
      retries: 10


networks:
  database:

volumes:
  mysql_data: